Search.appendIndex(
    [
                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\api\\API",
            "name": "API",
            "summary": "",
            "url": "classes/com-carlgo11-tempfiles-api-API.html"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\api\\API\u003A\u003AoutputJSON\u0028\u0029",
            "name": "outputJSON",
            "summary": "",
            "url": "classes/com-carlgo11-tempfiles-api-API.html#method_outputJSON"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\api\\Cleanup",
            "name": "Cleanup",
            "summary": "",
            "url": "classes/com-carlgo11-tempfiles-api-Cleanup.html"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\api\\Cleanup\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Cleanup\u0020constructor.",
            "url": "classes/com-carlgo11-tempfiles-api-Cleanup.html#method___construct"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\api\\Delete",
            "name": "Delete",
            "summary": "",
            "url": "classes/com-carlgo11-tempfiles-api-Delete.html"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\api\\Delete\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Delete\u0020constructor.",
            "url": "classes/com-carlgo11-tempfiles-api-Delete.html#method___construct"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\api\\Download",
            "name": "Download",
            "summary": "",
            "url": "classes/com-carlgo11-tempfiles-api-Download.html"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\api\\Download\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Download\u0020constructor.",
            "url": "classes/com-carlgo11-tempfiles-api-Download.html#method___construct"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\api\\Upload",
            "name": "Upload",
            "summary": "",
            "url": "classes/com-carlgo11-tempfiles-api-Upload.html"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\api\\Upload\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Upload\u0020constructor.",
            "url": "classes/com-carlgo11-tempfiles-api-Upload.html#method___construct"
        },                {
            "fqsen": "\\checkFile\u0028\u0029",
            "name": "checkFile",
            "summary": "Checks\u0020if\u0020a\u0020file\u0020exists.",
            "url": "namespaces/default.html#function_checkFile"
        },                {
            "fqsen": "\\createDirectory\u0028\u0029",
            "name": "createDirectory",
            "summary": "",
            "url": "namespaces/default.html#function_createDirectory"
        },                {
            "fqsen": "\\checkVars\u0028\u0029",
            "name": "checkVars",
            "summary": "",
            "url": "namespaces/default.html#function_checkVars"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\DataInterface",
            "name": "DataInterface",
            "summary": "",
            "url": "classes/com-carlgo11-tempfiles-datastorage-DataInterface.html"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\DataInterface\u003A\u003AgetEntryContent\u0028\u0029",
            "name": "getEntryContent",
            "summary": "Get\u0020encrypted\u0020content\u0020\u0028file\u0020data\u0029\u0020from\u0020a\u0020stored\u0020entry.",
            "url": "classes/com-carlgo11-tempfiles-datastorage-DataInterface.html#method_getEntryContent"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\DataInterface\u003A\u003AgetEntryMetaData\u0028\u0029",
            "name": "getEntryMetaData",
            "summary": "Get\u0020encrypted\u0020metadata.",
            "url": "classes/com-carlgo11-tempfiles-datastorage-DataInterface.html#method_getEntryMetaData"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\DataInterface\u003A\u003AsaveEntry\u0028\u0029",
            "name": "saveEntry",
            "summary": "Save\u0020an\u0020uploaded\u0020entry.",
            "url": "classes/com-carlgo11-tempfiles-datastorage-DataInterface.html#method_saveEntry"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\DataInterface\u003A\u003AentryExists\u0028\u0029",
            "name": "entryExists",
            "summary": "See\u0020if\u0020an\u0020entry\u0020with\u0020the\u0020provided\u0020ID\u0020exists.",
            "url": "classes/com-carlgo11-tempfiles-datastorage-DataInterface.html#method_entryExists"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\DataInterface\u003A\u003AdeleteEntry\u0028\u0029",
            "name": "deleteEntry",
            "summary": "Delete\u0020a\u0020stored\u0020entry\u0020\u0028file\u0029",
            "url": "classes/com-carlgo11-tempfiles-datastorage-DataInterface.html#method_deleteEntry"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\DataInterface\u003A\u003AgetEntryExpiry\u0028\u0029",
            "name": "getEntryExpiry",
            "summary": "Get\u0020the\u0020expiry\u0020date\u0020of\u0020a\u0020stored\u0020entry.",
            "url": "classes/com-carlgo11-tempfiles-datastorage-DataInterface.html#method_getEntryExpiry"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\DataInterface\u003A\u003AlistEntries\u0028\u0029",
            "name": "listEntries",
            "summary": "Get\u0020all\u0020stored\u0020entry\u0020IDs",
            "url": "classes/com-carlgo11-tempfiles-datastorage-DataInterface.html#method_listEntries"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\DataInterface\u003A\u003AgetDelPassword\u0028\u0029",
            "name": "getDelPassword",
            "summary": "Get\u0020Deletion\u0020password\u0020hash.",
            "url": "classes/com-carlgo11-tempfiles-datastorage-DataInterface.html#method_getDelPassword"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\DataStorage",
            "name": "DataStorage",
            "summary": "High\u0020level\u0020data\u0020storage\u0020handler.",
            "url": "classes/com-carlgo11-tempfiles-datastorage-DataStorage.html"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\DataStorage\u003A\u003AgetFile\u0028\u0029",
            "name": "getFile",
            "summary": "Get\u0020a\u0020stored\u0020entry.",
            "url": "classes/com-carlgo11-tempfiles-datastorage-DataStorage.html#method_getFile"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\DataStorage\u003A\u003AgetStorage\u0028\u0029",
            "name": "getStorage",
            "summary": "Get\u0020storage\u0020method\u0020specified\u0020in\u0020config.",
            "url": "classes/com-carlgo11-tempfiles-datastorage-DataStorage.html#method_getStorage"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\DataStorage\u003A\u003AsaveFile\u0028\u0029",
            "name": "saveFile",
            "summary": "Save\u0020an\u0020uploaded\u0020entry.",
            "url": "classes/com-carlgo11-tempfiles-datastorage-DataStorage.html#method_saveFile"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\DataStorage\u003A\u003AdeleteOldFiles\u0028\u0029",
            "name": "deleteOldFiles",
            "summary": "Delete\u0020all\u0020files\u0020older\u0020than\u002024\u0020hours.",
            "url": "classes/com-carlgo11-tempfiles-datastorage-DataStorage.html#method_deleteOldFiles"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\DataStorage\u003A\u003AdeleteFile\u0028\u0029",
            "name": "deleteFile",
            "summary": "Delete\u0020a\u0020stored\u0020entry.",
            "url": "classes/com-carlgo11-tempfiles-datastorage-DataStorage.html#method_deleteFile"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\DataStorage\u003A\u003AupdateViews\u0028\u0029",
            "name": "updateViews",
            "summary": "Update\u0020current\u0020views\u0020on\u0020existing\u0020entry.",
            "url": "classes/com-carlgo11-tempfiles-datastorage-DataStorage.html#method_updateViews"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\DataStorage\u003A\u003AgetDeletionPassword\u0028\u0029",
            "name": "getDeletionPassword",
            "summary": "",
            "url": "classes/com-carlgo11-tempfiles-datastorage-DataStorage.html#method_getDeletionPassword"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\FileStorage",
            "name": "FileStorage",
            "summary": "Local\u0020file\u0020storage\u0020class",
            "url": "classes/com-carlgo11-tempfiles-datastorage-FileStorage.html"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\FileStorage\u003A\u003AgetEntryContent\u0028\u0029",
            "name": "getEntryContent",
            "summary": "Get\u0020encrypted\u0020content\u0020\u0028file\u0020data\u0029\u0020from\u0020a\u0020stored\u0020entry.",
            "url": "classes/com-carlgo11-tempfiles-datastorage-FileStorage.html#method_getEntryContent"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\FileStorage\u003A\u003AentryExists\u0028\u0029",
            "name": "entryExists",
            "summary": "See\u0020if\u0020an\u0020entry\u0020with\u0020the\u0020provided\u0020ID\u0020exists.",
            "url": "classes/com-carlgo11-tempfiles-datastorage-FileStorage.html#method_entryExists"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\FileStorage\u003A\u003AgetEntryMetaData\u0028\u0029",
            "name": "getEntryMetaData",
            "summary": "Get\u0020encrypted\u0020metadata.",
            "url": "classes/com-carlgo11-tempfiles-datastorage-FileStorage.html#method_getEntryMetaData"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\FileStorage\u003A\u003AgetEntryViews\u0028\u0029",
            "name": "getEntryViews",
            "summary": "Get\u0020views\u0020and\u0020max\u0020views\u0020of\u0020a\u0020stored\u0020entry.",
            "url": "classes/com-carlgo11-tempfiles-datastorage-FileStorage.html#method_getEntryViews"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\FileStorage\u003A\u003AsaveEntry\u0028\u0029",
            "name": "saveEntry",
            "summary": "Save\u0020an\u0020uploaded\u0020entry.",
            "url": "classes/com-carlgo11-tempfiles-datastorage-FileStorage.html#method_saveEntry"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\FileStorage\u003A\u003AgetEntryExpiry\u0028\u0029",
            "name": "getEntryExpiry",
            "summary": "Get\u0020the\u0020expiry\u0020date\u0020of\u0020a\u0020stored\u0020entry.",
            "url": "classes/com-carlgo11-tempfiles-datastorage-FileStorage.html#method_getEntryExpiry"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\FileStorage\u003A\u003AdeleteEntry\u0028\u0029",
            "name": "deleteEntry",
            "summary": "Delete\u0020a\u0020stored\u0020entry\u0020\u0028file\u0029",
            "url": "classes/com-carlgo11-tempfiles-datastorage-FileStorage.html#method_deleteEntry"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\FileStorage\u003A\u003AlistEntries\u0028\u0029",
            "name": "listEntries",
            "summary": "Get\u0020all\u0020stored\u0020entry\u0020IDs",
            "url": "classes/com-carlgo11-tempfiles-datastorage-FileStorage.html#method_listEntries"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\FileStorage\u003A\u003AupdateEntryViews\u0028\u0029",
            "name": "updateEntryViews",
            "summary": "Update\u0020views\u0020array\u0020in\u0020stored\u0020entry\u0020file.",
            "url": "classes/com-carlgo11-tempfiles-datastorage-FileStorage.html#method_updateEntryViews"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\FileStorage\u003A\u003AgetDelPassword\u0028\u0029",
            "name": "getDelPassword",
            "summary": "Get\u0020Deletion\u0020password\u0020hash.",
            "url": "classes/com-carlgo11-tempfiles-datastorage-FileStorage.html#method_getDelPassword"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\MySQLStorage",
            "name": "MySQLStorage",
            "summary": "",
            "url": "classes/com-carlgo11-tempfiles-datastorage-MySQLStorage.html"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\MySQLStorage\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/com-carlgo11-tempfiles-datastorage-MySQLStorage.html#method___construct"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\MySQLStorage\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "",
            "url": "classes/com-carlgo11-tempfiles-datastorage-MySQLStorage.html#method___destruct"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\MySQLStorage\u003A\u003AgetEntryContent\u0028\u0029",
            "name": "getEntryContent",
            "summary": "Get\u0020encrypted\u0020content\u0020\u0028file\u0020data\u0029\u0020from\u0020a\u0020stored\u0020entry.",
            "url": "classes/com-carlgo11-tempfiles-datastorage-MySQLStorage.html#method_getEntryContent"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\MySQLStorage\u003A\u003AgetEntryMetaData\u0028\u0029",
            "name": "getEntryMetaData",
            "summary": "Get\u0020encrypted\u0020metadata.",
            "url": "classes/com-carlgo11-tempfiles-datastorage-MySQLStorage.html#method_getEntryMetaData"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\MySQLStorage\u003A\u003AsaveEntry\u0028\u0029",
            "name": "saveEntry",
            "summary": "Save\u0020an\u0020uploaded\u0020entry.",
            "url": "classes/com-carlgo11-tempfiles-datastorage-MySQLStorage.html#method_saveEntry"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\MySQLStorage\u003A\u003AentryExists\u0028\u0029",
            "name": "entryExists",
            "summary": "See\u0020if\u0020an\u0020entry\u0020with\u0020the\u0020provided\u0020ID\u0020exists.",
            "url": "classes/com-carlgo11-tempfiles-datastorage-MySQLStorage.html#method_entryExists"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\MySQLStorage\u003A\u003AdeleteEntry\u0028\u0029",
            "name": "deleteEntry",
            "summary": "Delete\u0020a\u0020stored\u0020entry\u0020\u0028file\u0029",
            "url": "classes/com-carlgo11-tempfiles-datastorage-MySQLStorage.html#method_deleteEntry"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\MySQLStorage\u003A\u003AgetEntryExpiry\u0028\u0029",
            "name": "getEntryExpiry",
            "summary": "Get\u0020the\u0020expiry\u0020date\u0020of\u0020a\u0020stored\u0020entry.",
            "url": "classes/com-carlgo11-tempfiles-datastorage-MySQLStorage.html#method_getEntryExpiry"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\MySQLStorage\u003A\u003AlistEntries\u0028\u0029",
            "name": "listEntries",
            "summary": "Get\u0020all\u0020stored\u0020entry\u0020IDs",
            "url": "classes/com-carlgo11-tempfiles-datastorage-MySQLStorage.html#method_listEntries"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\MySQLStorage\u003A\u003AgetDelPassword\u0028\u0029",
            "name": "getDelPassword",
            "summary": "Get\u0020Deletion\u0020password\u0020hash.",
            "url": "classes/com-carlgo11-tempfiles-datastorage-MySQLStorage.html#method_getDelPassword"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage\\MySQLStorage\u003A\u003A\u0024_mysql",
            "name": "_mysql",
            "summary": "",
            "url": "classes/com-carlgo11-tempfiles-datastorage-MySQLStorage.html#property__mysql"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\Encryption",
            "name": "Encryption",
            "summary": "Encryption\u0020handling.",
            "url": "classes/com-carlgo11-tempfiles-Encryption.html"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\Encryption\u003A\u003Aencrypt\u0028\u0029",
            "name": "encrypt",
            "summary": "Encrypts\u0020string\u0020with\u0020encryption\u0020algorithm\u0020specified\u0020in\u0020config",
            "url": "classes/com-carlgo11-tempfiles-Encryption.html#method_encrypt"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\Encryption\u003A\u003AcreateIV\u0028\u0029",
            "name": "createIV",
            "summary": "Create\u0020an\u0020IV\u0020\u0028Initialization\u0020Vector\u0029\u0020string.",
            "url": "classes/com-carlgo11-tempfiles-Encryption.html#method_createIV"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\Encryption\u003A\u003Adecrypt\u0028\u0029",
            "name": "decrypt",
            "summary": "",
            "url": "classes/com-carlgo11-tempfiles-Encryption.html#method_decrypt"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\exception\\BadMethod",
            "name": "BadMethod",
            "summary": "",
            "url": "classes/com-carlgo11-tempfiles-exception-BadMethod.html"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\exception\\BadMethod\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/com-carlgo11-tempfiles-exception-BadMethod.html#method___construct"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\exception\\MissingEntry",
            "name": "MissingEntry",
            "summary": "",
            "url": "classes/com-carlgo11-tempfiles-exception-MissingEntry.html"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\exception\\MissingEntry\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/com-carlgo11-tempfiles-exception-MissingEntry.html#method___construct"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\File",
            "name": "File",
            "summary": "File\u0020class\nStores\u0020all\u0020file\u002Drelated\u0020data\u0020during\u0020a\u0020file\u002Dupload\/\u002Ddownload\u0020operation.",
            "url": "classes/com-carlgo11-tempfiles-File.html"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\File\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Main\u0020function\u0020of\u0020File\u0020class.",
            "url": "classes/com-carlgo11-tempfiles-File.html#method___construct"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\File\u003A\u003AgenerateID\u0028\u0029",
            "name": "generateID",
            "summary": "Generates\u0020a\u0020new\u0020ID\u0020for\u0020the\u0020file.",
            "url": "classes/com-carlgo11-tempfiles-File.html#method_generateID"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\File\u003A\u003AsetID\u0028\u0029",
            "name": "setID",
            "summary": "Sets\u0020the\u0020ID\u0020of\u0020the\u0020file.",
            "url": "classes/com-carlgo11-tempfiles-File.html#method_setID"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\File\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "Gets\u0020ID\u0020of\u0020the\u0020file.",
            "url": "classes/com-carlgo11-tempfiles-File.html#method___toString"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\File\u003A\u003AgetID\u0028\u0029",
            "name": "getID",
            "summary": "Gets\u0020ID\u0020of\u0020the\u0020file.",
            "url": "classes/com-carlgo11-tempfiles-File.html#method_getID"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\File\u003A\u003AgetContent\u0028\u0029",
            "name": "getContent",
            "summary": "Gets\u0020file\u0020content.",
            "url": "classes/com-carlgo11-tempfiles-File.html#method_getContent"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\File\u003A\u003AsetContent\u0028\u0029",
            "name": "setContent",
            "summary": "Sets\u0020the\u0020content\u0020of\u0020the\u0020file.",
            "url": "classes/com-carlgo11-tempfiles-File.html#method_setContent"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\File\u003A\u003AgetCurrentViews\u0028\u0029",
            "name": "getCurrentViews",
            "summary": "Gets\u0020the\u0020current\u0020views\u0020of\u0020the\u0020file\u0020if\u0020available.",
            "url": "classes/com-carlgo11-tempfiles-File.html#method_getCurrentViews"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\File\u003A\u003AsetCurrentViews\u0028\u0029",
            "name": "setCurrentViews",
            "summary": "Sets\u0020the\u0020current\u0020views\/downloads\u0020of\u0020the\u0020file.",
            "url": "classes/com-carlgo11-tempfiles-File.html#method_setCurrentViews"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\File\u003A\u003AgetMaxViews\u0028\u0029",
            "name": "getMaxViews",
            "summary": "Gets\u0020the\u0020max\u0020available\u0020views\/downloads\u0020before\u0020the\u0020file\u0020gets\u0020deleted.",
            "url": "classes/com-carlgo11-tempfiles-File.html#method_getMaxViews"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\File\u003A\u003AsetMaxViews\u0028\u0029",
            "name": "setMaxViews",
            "summary": "Sets\u0020the\u0020max\u0020views\u0020of\u0020the\u0020file.",
            "url": "classes/com-carlgo11-tempfiles-File.html#method_setMaxViews"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\File\u003A\u003AgetDeletionPassword\u0028\u0029",
            "name": "getDeletionPassword",
            "summary": "Gets\u0020the\u0020deletion\u0020password\u0020of\u0020the\u0020file.",
            "url": "classes/com-carlgo11-tempfiles-File.html#method_getDeletionPassword"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\File\u003A\u003AsetDeletionPassword\u0028\u0029",
            "name": "setDeletionPassword",
            "summary": "Sets\u0020the\u0020deletion\u0020password\u0020of\u0020the\u0020file.",
            "url": "classes/com-carlgo11-tempfiles-File.html#method_setDeletionPassword"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\File\u003A\u003AgetMetaData\u0028\u0029",
            "name": "getMetaData",
            "summary": "Gets\u0020the\u0020metadata\u0020of\u0020the\u0020file\u0020if\u0020supplied.",
            "url": "classes/com-carlgo11-tempfiles-File.html#method_getMetaData"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\File\u003A\u003AsetMetaData\u0028\u0029",
            "name": "setMetaData",
            "summary": "Sets\u0020the\u0020metadata\u0020of\u0020the\u0020file.",
            "url": "classes/com-carlgo11-tempfiles-File.html#method_setMetaData"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\File\u003A\u003AgetIV\u0028\u0029",
            "name": "getIV",
            "summary": "",
            "url": "classes/com-carlgo11-tempfiles-File.html#method_getIV"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\File\u003A\u003AsetIV\u0028\u0029",
            "name": "setIV",
            "summary": "",
            "url": "classes/com-carlgo11-tempfiles-File.html#method_setIV"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\File\u003A\u003AsetDateTime\u0028\u0029",
            "name": "setDateTime",
            "summary": "Set\u0020deletion\u0020date\u0020\u0026\u0020time.",
            "url": "classes/com-carlgo11-tempfiles-File.html#method_setDateTime"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\File\u003A\u003AgetDateTime\u0028\u0029",
            "name": "getDateTime",
            "summary": "Get\u0020deletion\u0020date\u0020\u0026\u0020time.",
            "url": "classes/com-carlgo11-tempfiles-File.html#method_getDateTime"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\File\u003A\u003A\u0024_id",
            "name": "_id",
            "summary": "",
            "url": "classes/com-carlgo11-tempfiles-File.html#property__id"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\File\u003A\u003A\u0024_content",
            "name": "_content",
            "summary": "",
            "url": "classes/com-carlgo11-tempfiles-File.html#property__content"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\File\u003A\u003A\u0024_currentViews",
            "name": "_currentViews",
            "summary": "",
            "url": "classes/com-carlgo11-tempfiles-File.html#property__currentViews"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\File\u003A\u003A\u0024_maxViews",
            "name": "_maxViews",
            "summary": "",
            "url": "classes/com-carlgo11-tempfiles-File.html#property__maxViews"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\File\u003A\u003A\u0024_deletionPassword",
            "name": "_deletionPassword",
            "summary": "",
            "url": "classes/com-carlgo11-tempfiles-File.html#property__deletionPassword"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\File\u003A\u003A\u0024_metaData",
            "name": "_metaData",
            "summary": "",
            "url": "classes/com-carlgo11-tempfiles-File.html#property__metaData"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\File\u003A\u003A\u0024_iv",
            "name": "_iv",
            "summary": "",
            "url": "classes/com-carlgo11-tempfiles-File.html#property__iv"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\File\u003A\u003A\u0024_time",
            "name": "_time",
            "summary": "",
            "url": "classes/com-carlgo11-tempfiles-File.html#property__time"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\Misc",
            "name": "Misc",
            "summary": "Miscellaneous\u0020functions",
            "url": "classes/com-carlgo11-tempfiles-Misc.html"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\Misc\u003A\u003AgetVar\u0028\u0029",
            "name": "getVar",
            "summary": "Get\u0020a\u0020parameter\u0020from\u0020either\u0020\u0024_GET\u0020or\u0020\u0024_POST.",
            "url": "classes/com-carlgo11-tempfiles-Misc.html#method_getVar"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\Misc\u003A\u003AgeneratePassword\u0028\u0029",
            "name": "generatePassword",
            "summary": "Generate\u0020a\u0020password\u0020to\u0020use\u0020for\u0020encryption.",
            "url": "classes/com-carlgo11-tempfiles-Misc.html#method_generatePassword"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\api",
            "name": "api",
            "summary": "",
            "url": "namespaces/com-carlgo11-tempfiles-api.html"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\datastorage",
            "name": "datastorage",
            "summary": "",
            "url": "namespaces/com-carlgo11-tempfiles-datastorage.html"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles",
            "name": "tempfiles",
            "summary": "",
            "url": "namespaces/com-carlgo11-tempfiles.html"
        },                {
            "fqsen": "\\com\\carlgo11",
            "name": "carlgo11",
            "summary": "",
            "url": "namespaces/com-carlgo11.html"
        },                {
            "fqsen": "\\com",
            "name": "com",
            "summary": "",
            "url": "namespaces/com.html"
        },                {
            "fqsen": "\\com\\carlgo11\\tempfiles\\exception",
            "name": "exception",
            "summary": "",
            "url": "namespaces/com-carlgo11-tempfiles-exception.html"
        }            ]
);
