version: '3.2'
services:
  tmpfiles:
    build: .
    ports:
      - "5392:5392"
      - "5393:5393"
    volumes:
      - ./resources/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./resources/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./resources/cleanup.sh:/etc/periodic/hourly/cleanup
    restart: always
